### PR TITLE
FIX: [ui] prevent blank page when status is unknown

### LINKED ISSUE #210: blank page sometimes
**What happened**:
Some deployments cause statusbay to display blank page (to be precise - page renders correctly and then in split second rerenders blank). Why I think that is? Because when I set number of rows returned to not contain problematic deployment page loads normally. 

Contents of my firefox console when page is blank (normally this does not occur):
`TypeError: a is undefined
Tooltip.js:449:18
    P Tooltip.js:449
    React 6
    wl self-hosted:920
    Qi React
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    Aa self-hosted:977
    p ApplicationsHooks.js:43
    emit index.js:133
    onevent socket.js:278
    onpacket socket.js:240
    exports index.js:21
    emit index.js:133
    ondecoded manager.js:345
    exports index.js:21
    emit index.js:133
    add index.js:251
    ondata manager.js:335
    exports index.js:21
    emit index.js:133
    onPacket socket.js:461
    setTransport socket.js:278
    emit index.js:133
    onPacket transport.js:149
    onData transport.js:141
    onmessage websocket.js:156
TypeError: "a is undefined"
    P Tooltip.js:449
    React 7
        pa
        $a
        Ps
        Al
        Ml
        wl
        Qi
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
        Xi
        Qi
        Zi
        gl
        Aa
    p ApplicationsHooks.js:43
    emit index.js:133
    onevent socket.js:278
    onpacket socket.js:240
    exports index.js:21
    emit index.js:133
    ondecoded manager.js:345
    exports index.js:21
    emit index.js:133
    add index.js:251
    ondata manager.js:335
    exports index.js:21
    emit index.js:133
    onPacket socket.js:461
    setTransport socket.js:278
    emit index.js:133
    onPacket transport.js:149
    onData transport.js:141
    onmessage websocket.js:156`

**What you expected to happen**:
There should be something more useful than blank page generated.
**How to reproduce it (as minimally and precisely as possible)**:
Unfortunately - no idea ;)
**Anything else we need to know?**:

**Environment**:
- StatusBay version: latest from helm chart (as of 17.03.2020)
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others: Kubernetes 1.15.9

### PR DESCRIPTION
**Pull request by liorbd**
**What type of PR is this?**
 Bug

**Which issue(s) this PR fixes (if exists)**:
Fixes #210

### CODE REVIEW

**Comment by kaplanelad** [comment]
Hey @liorbd, 
Do we support `cancelled` status in fronted?

**Comment by liorbd** [comment]
@kaplanelad Currently no, This PR will prevent the blank page, and will display the status cell empty

**Comment by liorbd** [comment]
I've also added support for `cancelled` status is UI

**Comment by kaplanelad** [comment]
Thanks @liorbd.

**Pull request merged**
